# Generated by Django 5.2.4 on 2025-07-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='sitecontent',
            unique_together={('key', 'language')},
        ),
    ]
