# Generated by Django 5.2.4 on 2025-07-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitecontent_language_alter_sitecontent_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('language', models.CharField(default='en', max_length=10)),
                ('vimeo_url', models.URLField()),
                ('is_private', models.BooleanField(default=False)),
            ],
        ),
    ]
