# Generated by Django 5.2.4 on 2025-08-01 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('audiobook_sl_hl', 'Audiobook SL HL'), ('audiobook_hl_only', 'Audiobook HL only'), ('audiolibro_nm_ns', 'Audiolibro NM NS'), ('audiolibro_ns_solo', 'Audiolibro NS sólo'), ('notes_and_practice', 'Notes and practice'), ('notas_y_practica', 'Notas y práctica')], max_length=50)),
                ('chapter', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_resources', to='core.video')),
            ],
            options={
                'ordering': ['category', 'order', 'chapter'],
                'unique_together': {('category', 'chapter')},
            },
        ),
    ]
