# Generated by Django 5.2.4 on 2025-08-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chapterresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapterresource',
            name='video',
        ),
        migrations.AddField(
            model_name='chapterresource',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chapterresource',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='chapterresource',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chapterresource',
            name='vimeo_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
