# Generated by Django 5.2.4 on 2025-08-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_chapterresource_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterresource',
            name='drive_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='chapterresource',
            name='category',
            field=models.CharField(choices=[('audiobook_sl_hl', 'Audiobook SL HL'), ('audiobook_hl_only', 'Audiobook HL only'), ('audiolibro_nm_ns', 'Audiolibro NM NS'), ('audiolibro_ns_solo', 'Audiolibro NS sólo'), ('notes', 'Notes'), ('notas', 'Notas'), ('practice', 'Practice'), ('practica', 'Practica')], max_length=50),
        ),
    ]
