# Generated by Django 5.2.4 on 2025-08-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chapterresource_drive_url_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapterresource',
            unique_together={('category', 'chapter', 'description')},
        ),
    ]
