# Generated by Django 5.2.4 on 2025-08-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_chapterresource_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterresource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
