# Generated by Django 5.2.4 on 2025-07-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
