# Generated by Django 5.2.4 on 2025-08-17 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_has_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Alphanumeric code (you may include dashes).', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Code must be alphanumeric (dashes allowed).', regex='^[-A-Za-z0-9]+$')])),
                ('school', models.CharField(max_length=255)),
                ('total_accounts', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('remaining_accounts', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('who_paid', models.EmailField(max_length=254)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('invoice', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
